# Generated by Django 3.2.8 on 2021-10-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfile',
            name='sex',
        ),
        migrations.AddField(
            model_name='patientfile',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=1),
        ),
    ]
