# Generated by Django 3.2.9 on 2021-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='algo',
            field=models.CharField(blank=True, choices=[('', ''), ('Belge', 'Belge'), ('Français', 'Français'), ('Européen', 'Européen')], max_length=40, verbose_name='Algorithme suivi'),
        ),
    ]
