# Generated by Django 3.2.9 on 2021-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(blank=True, choices=[('Prévention primaire', 'Prévention primaire'), ('Prévention secondaire', 'Prévention secondaire'), ('Fibrilation Atriale', 'Fibrilation Atriale'), ('Valvulopathie', 'Valvulopathie'), ('Pontages Cardiaques', 'Pontages Cardiaques'), ('Chirurgie Vasculaire Arterielle', 'Chirurgie Vasculaire Arterielle'), ('ATCD EP', 'ATCD EP'), ('ATCD TVP', 'ATCD TVP'), ('ATCD AVC + AIT', 'ATCD AVC + AIT'), ('CMI', 'CMI'), ('Stents Cardiaques', 'Stents Cardiaques'), ('Greffe', 'Greffe'), ('Thrombose Porte', 'Thrombose Porte'), ('Thrombose Mesenterique', 'Thrombose Mesenterique')], max_length=40, null=True, verbose_name='Pathologie justifiant le traitement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='traitement1',
            field=models.CharField(blank=True, choices=[('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], max_length=40, null=True, verbose_name='Premier traitement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='traitement2',
            field=models.CharField(blank=True, choices=[('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], max_length=40, null=True, verbose_name='Deuxième traitement'),
        ),
    ]
