# Generated by Django 3.2.9 on 2021-11-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_algo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hosp_num',
        ),
    ]
