# Generated by Django 3.2.8 on 2021-11-01 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('incl_num', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(verbose_name='taille')),
                ('weight', models.IntegerField(verbose_name='poids')),
                ('ddn', models.DateTimeField(verbose_name='Date de naissance')),
                ('ddi', models.DateTimeField(verbose_name="Date de l'intervention")),
                ('intervention', models.CharField(default='', max_length=200, verbose_name='intervention')),
                ('chirurgie', models.CharField(choices=[('Chirurgie Cardiaque', 'Chirurgie Cardiaque'), ('Chirurgie Digestive', 'Chirurgie Digestive'), ('Chirurgie Gynecologique', 'Chirurgie Gynecologique'), ('Chirurgie Hepatique', 'Chirurgie Hepatique'), ('Chirurgie Orthopedique', 'Chirurgie Orthopedique'), ('Chirurgie Ophtalmologique', 'Chirurgie Ophtalmologique'), ('Chirurgie Plastique', 'Chirurgie Plastique'), ('Chirurgie Thoracique', 'Chirurgie Thoracique'), ('Chirurgie Urologique', 'Chirurgie Urologique'), ('Endoscopie', 'Endoscopie'), ('Neurochirurgie', 'Neurochirurgie'), ('Chirurgie ORL', 'Chirurgie ORL'), ('Radiologie Interventionnelle', 'Radiologie Interventionnelle'), ('Stomatologie', 'Stomatologie')], default='Chirurgie Cardiaque', max_length=40, verbose_name="Discipline de l'intervention")),
                ('pathologie', models.CharField(choices=[('Prévention primaire', 'Prévention primaire'), ('Prévention secondaire', 'Prévention secondaire'), ('Fibrilation Atriale', 'Fibrilation Atriale'), ('Valvulopathie', 'Valvulopathie'), ('Pontages Cardiaques', 'Pontages Cardiaques'), ('Chirurgie Vasculaire Arterielle', 'Chirurgie Vasculaire Arterielle'), ('ATCD EP', 'ATCD EP'), ('ATCD TVP', 'ATCD TVP'), ('ATCD AVC + AIT', 'ATCD AVC + AIT'), ('CMI', 'CMI'), ('Stents Cardiaques', 'Stents Cardiaques'), ('Greffe', 'Greffe'), ('Thrombose Porte', 'Thrombose Porte'), ('Thrombose Mesenterique', 'Thrombose Mesenterique')], default='Prévention primaire', max_length=40, verbose_name='Pathologie justifiant le traitement')),
                ('traitement1', models.CharField(choices=[('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], default='Aspirine, Asaflow, Cardioaspirine', max_length=40, verbose_name='Premier traitement')),
                ('traitement2', models.CharField(choices=[('Aucun', 'Aucun'), ('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], default='Aucun', max_length=40, verbose_name='Deuxième traitement')),
                ('resultats', jsonfield.fields.JSONField()),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
