# Generated by Django 3.2.8 on 2021-11-01 01:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='resultats',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
