# Generated by Django 3.2.9 on 2021-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_resultats'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aptt',
            field=models.IntegerField(blank=True, null=True, verbose_name='APTT'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dfg',
            field=models.IntegerField(blank=True, null=True, verbose_name='DFG'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hémoglobine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='inr',
            field=models.IntegerField(blank=True, null=True, verbose_name='INR'),
        ),
        migrations.AddField(
            model_name='patient',
            name='plaquette',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plaquettes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pt',
            field=models.IntegerField(blank=True, null=True, verbose_name='PT'),
        ),
        migrations.AddField(
            model_name='patient',
            name='vol_sang',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume de saignement peropératoire'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chirurgie',
            field=models.CharField(blank=True, choices=[('-0', '-0'), ('-1', '-1'), ('-2', '-2'), ('-3', '-3'), ('-4', '-4'), ('-5', '-5'), ('+5', '+5'), ('+4', '+4'), ('+3', '+3'), ('+2', '+2'), ('+1', '+1'), ('+0', '+0')], default='-5', max_length=2, verbose_name='Qualité de la coagulation selon le chirurgien'),
        ),
    ]
