# Generated by Django 3.2.9 on 2021-11-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20211103_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_derniere_prise',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière prise pratique'),
        ),
        migrations.AddField(
            model_name='patient',
            name='inobservance',
            field=models.CharField(blank=True, choices=[("Pas d'inobservance", "Pas d'inobservance"), ('Oubli', 'Oubli'), ('Incompréhension', 'Incompréhension'), ('Contre-ordre médical', 'Contre-ordre médical')], default="Pas d'inobservance", max_length=40, verbose_name='Inobservance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='schema_therap',
            field=models.CharField(blank=True, choices=[('Date exacte', 'Date exacte'), ("Terminologie 'dernière prise à J-xx'", "Terminologie 'dernière prise à J-xx'"), ("Pas d'arrêt du traitement", "Pas d'arrêt du traitement")], default='Date exacte', max_length=40, verbose_name='Schéma thérapeutique donné au patient'),
        ),
    ]
