# Generated by Django 3.2.9 on 2021-11-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20211103_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='coag',
            field=models.CharField(choices=[('-0', '-0'), ('-1', '-1'), ('-2', '-2'), ('-3', '-3'), ('-4', '-4'), ('-5', '-5'), ('+5', '+5'), ('+4', '+4'), ('+3', '+3'), ('+2', '+2'), ('+1', '+1'), ('+0', '+0')], default='-5', max_length=2, verbose_name='Qualité de la coagulation selon le chirurgien'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inobservance',
            field=models.CharField(choices=[("Pas d'inobservance", "Pas d'inobservance"), ('Oubli', 'Oubli'), ('Incompréhension', 'Incompréhension'), ('Contre-ordre médical', 'Contre-ordre médical')], default="Pas d'inobservance", max_length=40, verbose_name='Inobservance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='schema_therap',
            field=models.CharField(choices=[('Date exacte', 'Date exacte'), ("Terminologie 'dernière prise à J-xx'", "Terminologie 'dernière prise à J-xx'"), ("Pas d'arrêt du traitement", "Pas d'arrêt du traitement")], default='Date exacte', max_length=40, verbose_name='Schéma thérapeutique donné au patient'),
        ),
    ]
