# Generated by Django 3.2.9 on 2021-11-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20211104_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_derniere_prise',
            new_name='date_derniere_prise1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='inobservance',
            new_name='inobservance1',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_derniere_prise2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière prise pratique'),
        ),
        migrations.AddField(
            model_name='patient',
            name='inobservance2',
            field=models.CharField(choices=[("Pas d'inobservance", "Pas d'inobservance"), ('Oubli', 'Oubli'), ('Incompréhension', 'Incompréhension'), ('Contre-ordre médical', 'Contre-ordre médical')], default="Pas d'inobservance", max_length=40, verbose_name='Inobservance'),
        ),
    ]
