# Generated by Django 3.2.9 on 2021-11-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20211104_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_derniere_prise1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière prise pratique (premier traitement)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_derniere_prise2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière prise pratique (deuxième traitement)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inobservance1',
            field=models.CharField(choices=[("Pas d'inobservance", "Pas d'inobservance"), ('Oubli', 'Oubli'), ('Incompréhension', 'Incompréhension'), ('Contre-ordre médical', 'Contre-ordre médical')], default="Pas d'inobservance", max_length=40, verbose_name='Inobservance (premier traitement)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='inobservance2',
            field=models.CharField(choices=[("Pas d'inobservance", "Pas d'inobservance"), ('Oubli', 'Oubli'), ('Incompréhension', 'Incompréhension'), ('Contre-ordre médical', 'Contre-ordre médical')], default="Pas d'inobservance", max_length=40, verbose_name='Inobservance (deuxième traitement)'),
        ),
    ]
