# Generated by Django 3.2.8 on 2021-10-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('incl_num', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField(verbose_name='taille')),
                ('weight', models.FloatField(verbose_name='poids')),
                ('ddn', models.DateTimeField(verbose_name='Date de naissance')),
                ('ddi', models.DateTimeField(verbose_name="Date de l'intervention")),
                ('intervention', models.CharField(max_length=200, verbose_name='intervention')),
                ('chirurgie', models.CharField(choices=[('CCA', 'Chirurgie Cardiaque'), ('CDI', 'Chirurgie Digestive'), ('CGY', 'Chirurgie Gynecologique'), ('CHE', 'Chirurgie Hepatique'), ('COR', 'Chirurgie Orthopedique'), ('COP', 'Chirurgie Ophtalmologique'), ('CPL', 'Chirurgie Plastique'), ('CTH', 'Chirurgie Thoracique'), ('CUR', 'Chirurgie Urologique'), ('END', 'Endoscopie'), ('NEU', 'Neurochirurgie'), ('ORL', 'Chirurgie ORL'), ('RIN', 'Radiologie Interventionnelle'), ('STO', 'Stomatologie')], default='CCA', max_length=3, verbose_name="Discipline de l'intervention")),
                ('pathologie', models.CharField(choices=[('PPR', 'Prevention primaire'), ('PSE', 'Prevention secondaire'), ('FAR', 'Fibrilation Atriale'), ('VAL', 'Valvulopathie'), ('PCA', 'Pontages Cardiaques'), ('CVA', 'Chirurgie Vasculaire Arterielle'), ('AEP', 'ATCD EP'), ('TVP', 'ATCD TVP'), ('AIT', 'ATCD AVC + AIT'), ('CMI', 'CMI'), ('SCA', 'Stents Cardiaques'), ('GRE', 'Greffe'), ('TPO', 'Thrombose Porte'), ('TME', 'Thrombose Mesenterique')], default='PPR', max_length=3, verbose_name='Pathologie justifiant le traitement')),
                ('traitement1', models.CharField(choices=[('Aspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel', 'Clopidogrel, PLAVIX'), ('Prasugrel', 'Prasugrel, EFFIENT'), ('Ticlopidine', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor', 'Ticagrelor, BRILIQUE'), ('Acenocoumarol', 'Acénocoumarol, SINTROM'), ('Phenprocoumone', 'Phenprocoumone, MARCOUMAR'), ('Warfarine', 'Warfarine, MAREVAN'), ('Apixaban', 'Apixaban, ELIQUIS'), ('Dabigatran', 'Dabigatran, PRADAXA'), ('Edoxaban', 'Edoxaban, LIXIANA'), ('Rivaroxaban', 'Rivaroxaban, XARELTO'), ('Enoxaparine', 'Enoxaparine, CLEXANE'), ('Nadroparine', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine', 'Tinzaparine, INNOHEP'), ('Fondaparinux', 'Fondaparinux, ARIXTRA'), ('HNF', 'HNF, Héparine Sodique')], default='Aspirine', max_length=15, verbose_name='Premier traitement')),
                ('traitement2', models.CharField(choices=[('Aucun', 'Aucun'), ('Aspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel', 'Clopidogrel, PLAVIX'), ('Prasugrel', 'Prasugrel, EFFIENT'), ('Ticlopidine', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor', 'Ticagrelor, BRILIQUE'), ('Acenocoumarol', 'Acénocoumarol, SINTROM'), ('Phenprocoumone', 'Phenprocoumone, MARCOUMAR'), ('Warfarine', 'Warfarine, MAREVAN'), ('Apixaban', 'Apixaban, ELIQUIS'), ('Dabigatran', 'Dabigatran, PRADAXA'), ('Edoxaban', 'Edoxaban, LIXIANA'), ('Rivaroxaban', 'Rivaroxaban, XARELTO'), ('Enoxaparine', 'Enoxaparine, CLEXANE'), ('Nadroparine', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine', 'Tinzaparine, INNOHEP'), ('Fondaparinux', 'Fondaparinux, ARIXTRA'), ('HNF', 'HNF, Héparine Sodique')], default='Aucun', max_length=15, verbose_name='Deuxième traitement')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
