# Generated by Django 3.2.8 on 2021-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='chirurgie',
            field=models.CharField(choices=[('Chirurgie Cardiaque', 'Chirurgie Cardiaque'), ('Chirurgie Digestive', 'Chirurgie Digestive'), ('Chirurgie Gynecologique', 'Chirurgie Gynecologique'), ('Chirurgie Hepatique', 'Chirurgie Hepatique'), ('Chirurgie Orthopedique', 'Chirurgie Orthopedique'), ('Chirurgie Ophtalmologique', 'Chirurgie Ophtalmologique'), ('Chirurgie Plastique', 'Chirurgie Plastique'), ('Chirurgie Thoracique', 'Chirurgie Thoracique'), ('Chirurgie Urologique', 'Chirurgie Urologique'), ('Endoscopie', 'Endoscopie'), ('Neurochirurgie', 'Neurochirurgie'), ('Chirurgie ORL', 'Chirurgie ORL'), ('Radiologie Interventionnelle', 'Radiologie Interventionnelle'), ('Stomatologie', 'Stomatologie')], default='Chirurgie Cardiaque', max_length=40, verbose_name="Discipline de l'intervention"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(choices=[('PPR', 'Prevention primaire'), ('PSE', 'Prevention secondaire'), ('FAR', 'Fibrilation Atriale'), ('VAL', 'Valvulopathie'), ('PCA', 'Pontages Cardiaques'), ('CVA', 'Chirurgie Vasculaire Arterielle'), ('AEP', 'ATCD EP'), ('TVP', 'ATCD TVP'), ('AIT', 'ATCD AVC + AIT'), ('CMI', 'CMI'), ('SCA', 'Stents Cardiaques'), ('GRE', 'Greffe'), ('TPO', 'Thrombose Porte'), ('TME', 'Thrombose Mesenterique')], default='PPR', max_length=40, verbose_name='Pathologie justifiant le traitement'),
        ),
    ]
