# Generated by Django 3.2.8 on 2021-10-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0002_auto_20211024_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pathologie',
            field=models.CharField(choices=[('Prevention primaire', 'Prevention primaire'), ('Prevention secondaire', 'Prevention secondaire'), ('Fibrilation Atriale', 'Fibrilation Atriale'), ('Valvulopathie', 'Valvulopathie'), ('Pontages Cardiaques', 'Pontages Cardiaques'), ('Chirurgie Vasculaire Arterielle', 'Chirurgie Vasculaire Arterielle'), ('ATCD EP', 'ATCD EP'), ('ATCD TVP', 'ATCD TVP'), ('ATCD AVC + AIT', 'ATCD AVC + AIT'), ('CMI', 'CMI'), ('Stents Cardiaques', 'Stents Cardiaques'), ('Greffe', 'Greffe'), ('Thrombose Porte', 'Thrombose Porte'), ('Thrombose Mesenterique', 'Thrombose Mesenterique')], default='Prevention primaire', max_length=40, verbose_name='Pathologie justifiant le traitement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='traitement1',
            field=models.CharField(choices=[('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], default='Aspirine, Asaflow, Cardioaspirine', max_length=40, verbose_name='Premier traitement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='traitement2',
            field=models.CharField(choices=[('Aucun', 'Aucun'), ('Aspirine, Asaflow, Cardioaspirine', 'Aspirine, Asaflow, Cardioaspirine'), ('Clopidogrel, PLAVIX', 'Clopidogrel, PLAVIX'), ('Prasugrel, EFFIENT', 'Prasugrel, EFFIENT'), ('Ticlopidine, TICLID', 'Ticlopidine, TICLID'), ('Dipyridamole', 'Dipyridamole'), ('Ticagrelor, BRILIQUE', 'Ticagrelor, BRILIQUE'), ('Acénocoumarol, SINTROM', 'Acénocoumarol, SINTROM'), ('Phenprocoumone, MARCOUMAR', 'Phenprocoumone, MARCOUMAR'), ('Warfarine, MAREVAN', 'Warfarine, MAREVAN'), ('Apixaban, ELIQUIS', 'Apixaban, ELIQUIS'), ('Dabigatran, PRADAXA', 'Dabigatran, PRADAXA'), ('Edoxaban, LIXIANA', 'Edoxaban, LIXIANA'), ('Rivaroxaban, XARELTO', 'Rivaroxaban, XARELTO'), ('Enoxaparine, CLEXANE', 'Enoxaparine, CLEXANE'), ('Nadroparine, FRAXIPARINE, FRAXODI', 'Nadroparine, FRAXIPARINE, FRAXODI'), ('Tinzaparine, INNOHEP', 'Tinzaparine, INNOHEP'), ('Fondaparinux, ARIXTRA', 'Fondaparinux, ARIXTRA'), ('HNF, Héparine Sodique', 'HNF, Héparine Sodique')], default='Aucun', max_length=40, verbose_name='Deuxième traitement'),
        ),
    ]
