# Generated by Django 3.2.8 on 2021-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusion', '0003_auto_20211024_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(verbose_name='taille'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='intervention',
            field=models.CharField(default='', max_length=200, verbose_name='intervention'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(verbose_name='poids'),
        ),
    ]
